service: cart-service

plugins:
  - serverless-offline
  - serverless-dotenv-plugin

useDotenv: true

provider:
  name: aws
  region: us-east-1
  runtime: nodejs18.x
  timeout: 15

functions:
  main:
    handler: dist/main.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
